Vagrant.configure("2") do |config|
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "gusztavvargadr/windows-10"
    config.vm.network "private_network", type: "dhcp"
end
